{% set name = "owa-core" %}
{% set version = "0.4.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_core-{{ version }}.tar.gz
  sha256: 74955db2344765ee97eb728065313bd88e6705043c98758facdef4d713304d35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - av >=14.4.0
    - loguru >=0.7.3
    - pydantic >=2.10.6
    - griffe >=1.7.3
    - owa-msgs
    - pyyaml >=6.0.2

test:
  imports:
    - owa.core
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: "Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
