{% set name = "owa-core" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_core-{{ version }}.tar.gz
  sha256: 215893203216c14526f99f018c5dc1ff48ae477188b904db16f2dbdc6ea39c23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opencv >=4.11.0
    - loguru >=0.7.3
    - pydantic >=2.10.6

test:
  imports:
    - owa.core
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: "Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
